module.exports = {
    normalArticle : [
        {
            id : "1",
            path : "/img_10.jpg",
            otherImage : "/prog.png",
            ArticleHeading : "Catch Waves With an adventure Guide1",
            description : "Gujrat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist designation.",
            completeInfo : "Spending time at national parks can be an exciting adventure, but this wasn't the type of excitement she was hoping to experience. As she contemplated the situation she found herself in, she knew she'd gotten herself in a little more than she bargained for. It wasn't often that she found herself in a tree staring down at a pack of wolves that were looking to make her their next meal.The spot was perfect for camouflage. At least that's what she thought when she picked the spot. She couldn't imagine that anyone would ever be able to see her in these surroundings. So there she sat, confident that she was hidden from the world and safe from danger. Unfortunately, she had not anticipated that others may be looking upon her from other angles, and now they were stealthily descending toward her hiding spot.",
            blogType : "Travel",
            date : "August 21 2017",
            authorName : "Rajput Harshilsinh",
            authorImage : "/avtar.png",
            readTime : "10 min",
            instagramId : "https://www.instagram.com/",
            facebookId : "https://www.facebook.com/",
            linkedinID : "https://in.linkedin.com/",
            youtubeId : "https://www.youtube.com/"
         },
        {
            id : "2",
            path : "/img_8.jpeg",
            otherImage : "/prog.png",
            ArticleHeading : "Catch Waves With an adventure Guide2",
            description : "Gujrat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist designation.",
            completeInfo : "Sometimes it's simply better to ignore the haters. That's the lesson that Tom's dad had been trying to teach him, but Tom still couldn't let it go. He latched onto them and their hate and couldn't let it go, but he also realized that this wasn't healthy. That's when he came up with his devious plan.The shoes had been there for as long as anyone could remember. In fact, it was difficult for anyone to come up with a date they had first appeared. It had seemed they'd always been there and yet they seemed so out of place. Why nobody had removed them was a question that had been asked time and again, but while they all thought it, nobody had ever found the energy to actually do it. So, the shoes remained on the steps, out of place in one sense, but perfectly normal in another.",
            blogType : "Travel",
            date : "August 21 2017",
            authorName : "Steve Smith",
            authorImage : "/avtar.png",
            readTime : "10 min",
            instagramId : "https://www.instagram.com/",
            facebookId : "https://www.facebook.com/",
            linkedinID : "https://in.linkedin.com/",
            youtubeId : "https://www.youtube.com/"
        },
        {
            id : "3",
            path : "/img_5.jpg",
            otherImage : "/prog.png",
            ArticleHeading : "Catch Waves With an adventure Guide3",
            description : "Gujrat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist designation.",
            completeInfo : "She reached her goal, exhausted. Even more chilling to her was that the euphoria that she thought she'd feel upon reaching it wasn't there. Something wasn't right. Was this the only feeling she'd have for over five years of hard work?The boy walked down the street in a carefree way, playing without notice of what was about him. He didn't hear the sound of the car as his ball careened into the road. He took a step toward it, and in doing so sealed his fate.",
            blogType : "Travel",
            date : "August 21 2017",
            authorName : "Martin Guptil",
            authorImage : "/avtar.png",
            readTime : "10 min",
            instagramId : "https://www.instagram.com/",
            facebookId : "https://www.facebook.com/",
            linkedinID : "https://in.linkedin.com/",
            youtubeId : "https://www.youtube.com/"
        },
        {
            id : "4",
            path : "/img_6.jpg",
            otherImage : "/prog.png",
            ArticleHeading : "Catch Waves With an adventure Guide4",
            description : "Gujrat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist designation.",
            completeInfo : "Sitting in the sun, away from everyone who had done him harm in the past, he quietly listened to those who roamed by. He felt at peace in the moment, hoping it would last, but knowing the reprieve would soon come to an end. He closed his eyes, the sun beating down on face and he smiled. He smiled for the first time in as long as he could remember.",
            blogType : "Travel",
            date : "August 21 2017",
            authorName : "David Warner",
            authorImage : "/avtar.png",
            readTime : "10 min",
            instagramId : "https://www.instagram.com/",
            facebookId : "https://www.facebook.com/",
            linkedinID : "https://in.linkedin.com/",
            youtubeId : "https://www.youtube.com/"
        },
        {
            id : "5",
            path : "/img_7.jpg",
            otherImage : "/prog.png",
            ArticleHeading : "Catch Waves With an adventure Guide5",
            description : "Gujrat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist designation.",
            completeInfo : "I haven't bailed on writing. Look, I'm generating a random paragraph at this very moment in an attempt to get my writing back on track. I am making an effort. I will start writing consistently again!There was little doubt that the bridge was unsafe. All one had to do was look at it to know that with certainty. Yet Bob didn't see another option. He may have been able to work one out if he had a bit of time to think things through, but time was something he didn't have. A choice needed to be made, and it needed to be made quickly.",
            blogType : "Travel",
            date : "August 21 2017",
            authorName : "Ben stockes",
            authorImage : "/avtar.png",
            readTime : "10 min",
            instagramId : "https://www.instagram.com/",
            facebookId : "https://www.facebook.com/",
            linkedinID : "https://in.linkedin.com/",
            youtubeId : "https://www.youtube.com/"
        },
        {
            id : "6",
            path : "/img_9.jpg",
            otherImage : "/prog.png",
            ArticleHeading : "Catch Waves With an adventure Guide6",
            description : "Gujrat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist designation.",
            completeInfo : "Green vines attached to the trunk of the tree had wound themselves toward the top of the canopy. Ants used the vine as their private highway, avoiding all the creases and crags of the bark, to freely move at top speed from top to bottom or bottom to top depending on their current chore. At least this was the way it was supposed to be. Something had damaged the vine overnight halfway up the tree leaving a gap in the once pristine ant highway.",
            blogType : "Travel",
            date : "August 21 2017",
            authorName : "Moen Ali",
            authorImage : "/avtar.png",
            readTime : "10 min",
            instagramId : "https://www.instagram.com/",
            facebookId : "https://www.facebook.com/",
            linkedinID : "https://in.linkedin.com/",
            youtubeId : "https://www.youtube.com/"
        },
        {
            id : "7",
            path : "/img_1.jpg",
            otherImage : "/prog.png",
            ArticleHeading : "Catch Waves With an adventure Guide7",
            description : "Gujrat is vastly underrated and it's a mystery to us why the region isn't more well known as a tourist designation.",
            completeInfo : "Turning away from the ledge, he started slowly down the mountain, deciding that he would, that very night, satisfy his curiosity about the man-house. In the meantime, he would go down into the canyon and get a cool drink, after which he would visit some berry patches just over the ridge, and explore among the foothills a bit before his nap-time, which always came just after the sun had walked past the middle of the sky. At that period of the day the sun’s warm rays seemed to cast a sleepy spell over the silent mountainside, so all of the animals, with one accord, had decided it should be the hour for their mid-day sleep.",
            blogType : "Travel",
            date : "August 21 2017",
            authorName : "Jason Roy",
            authorImage : "/avtar.png",
            readTime : "10 min",
            instagramId : "https://www.instagram.com/",
            facebookId : "https://www.facebook.com/",
            linkedinID : "https://in.linkedin.com/",
            youtubeId : "https://www.youtube.com/"
        }
    ],
    TopPostData :
    [
        {
            path : "/img_11.jpg",
            otherImage : "/prog.png",
            ArticleHeading : "Catch Waves With an adventure guide1",
            completeInfo : "Turning away from the ledge, he started slowly down the mountain, deciding that he would, that very night, satisfy his curiosity about the man-house. In the meantime, he would go down into the canyon and get a cool drink, after which he would visit some berry patches just over the ridge, and explore among the foothills a bit before his nap-time, which always came just after the sun had walked past the middle of the sky. At that period of the day the sun’s warm rays seemed to cast a sleepy spell over the silent mountainside, so all of the animals, with one accord, had decided it should be the hour for their mid-day sleep.",
            type : "Travel",
            date : "August 2017",
            number : "1",
            authorName : "Jason Roy",
            authorImage : "/avtar.png",
            readTime : "10 min",
            instagramId : "https://www.instagram.com/",
            facebookId : "https://www.facebook.com/",
            linkedinID : "https://in.linkedin.com/",
            youtubeId : "https://www.youtube.com/"
        },
        {
            path : "/img_6.jpg",
            otherImage : "/prog.png",
            ArticleHeading : "Catch Waves With an adventure guide2",
            completeInfo : "Green vines attached to the trunk of the tree had wound themselves toward the top of the canopy. Ants used the vine as their private highway, avoiding all the creases and crags of the bark, to freely move at top speed from top to bottom or bottom to top depending on their current chore. At least this was the way it was supposed to be. Something had damaged the vine overnight halfway up the tree leaving a gap in the once pristine ant highway.",
            type : "Travel",
            date : "August 2017",
            number : "2",
            authorName : "Rajput Harshilsinh",
            authorImage : "/avtar.png",
            readTime : "10 min",
            instagramId : "https://www.instagram.com/",
            facebookId : "https://www.facebook.com/",
            linkedinID : "https://in.linkedin.com/",
            youtubeId : "https://www.youtube.com/"
        },
        {
            path : "/img_9.jpg",
            otherImage : "/prog.png",
            ArticleHeading : "Catch Waves With an adventure guide3",
            completeInfo : "I haven't bailed on writing. Look, I'm generating a random paragraph at this very moment in an attempt to get my writing back on track. I am making an effort. I will start writing consistently again!There was little doubt that the bridge was unsafe. All one had to do was look at it to know that with certainty. Yet Bob didn't see another option. He may have been able to work one out if he had a bit of time to think things through, but time was something he didn't have. A choice needed to be made, and it needed to be made quickly.",
            type : "Travel",
            date : "August 2017",
            number : "3",
            authorName : "Steve Smith",
            authorImage : "/avtar.png",
            readTime : "10 min",
            instagramId : "https://www.instagram.com/",
            facebookId : "https://www.facebook.com/",
            linkedinID : "https://in.linkedin.com/",
            youtubeId : "https://www.youtube.com/"
        },
        {
            path : "/img_7.jpg",
            otherImage : "/prog.png",
            ArticleHeading : "Catch Waves With an adventure guide4",
            completeInfo : "Sometimes it's simply better to ignore the haters. That's the lesson that Tom's dad had been trying to teach him, but Tom still couldn't let it go. He latched onto them and their hate and couldn't let it go, but he also realized that this wasn't healthy. That's when he came up with his devious plan.The shoes had been there for as long as anyone could remember. In fact, it was difficult for anyone to come up with a date they had first appeared. It had seemed they'd always been there and yet they seemed so out of place. Why nobody had removed them was a question that had been asked time and again, but while they all thought it, nobody had ever found the energy to actually do it. So, the shoes remained on the steps, out of place in one sense, but perfectly normal in another.",
            type : "Travel",
            date : "August 2017",
            number : "4",
            authorName : "Kane Williamsan",
            authorImage : "/avtar.png",
            readTime : "10 min",
            instagramId : "https://www.instagram.com/",
            facebookId : "https://www.facebook.com/",
            linkedinID : "https://in.linkedin.com/",
            youtubeId : "https://www.youtube.com/"
        }
    ]
}